# -*- coding: utf-8 -*-
"""Tugas2_Peprocessing Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KBFgGT01XF_HL5ygt1NqBnNB5ombvQJd
"""

base_path = '/content/drive/MyDrive/archive/rps-cv-images'

from keras.preprocessing.image import ImageDataGenerator

generator = ImageDataGenerator (
    horizontal_flip = True,
    vertical_flip = True,
    height_shift_range = .2,
    validation_split = 0.2
)

train_image = generator.flow_from_directory(
    base_path,
    target_size=(224, 224),
    classes=['paper', 'rock', 'scissors'],
    class_mode='categorical',
    subset='training',
    shuffle=False,
)

val_image = generator.flow_from_directory(
    base_path,
    target_size=(224, 224),
    classes=['paper', 'rock', 'scissors'],
    class_mode='categorical',
    subset='validation',
    shuffle=True
)

print(train_image[0])